---
apiVersion: v1
kind: Namespace
metadata:
  name: safelink
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: safelink
  name: deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: skyway
  replicas: 1 
  template:
    metadata:
      labels:
        app.kubernetes.io/name: skyway
    spec:
      containers:
      - image: aaram/k8s-test:latest
        imagePullPolicy: Always
        name: skyway
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: safelink
  name: service
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: skyway
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: safelink
  name: ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: service
              port:
                number: 80